services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sti_db
      MYSQL_USER: sti_user
      MYSQL_PASSWORD: sti_password
    ports:
      - "3306:3306"
    volumes:
      - ../db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"